Financiamento
int Financiamento::numeroVezes
double Financiamento::valorParcela
double Financiamento::valorTotalFinanciado
Financiamento::Financiamento(int nVezes, double vParcela)
References setNumeroVezes, setValorParcela, setValorTotalFinanciado.
int Financiamento::getNumeroVezes()
double Financiamento::getValorParcela()
double Financiamento::getValorTotalFinanciado()
Referenced by SimulacaoFacade::compararInvestimentoEFinanciamento.
void Financiamento::setNumeroVezes(int n)
Referenced by Financiamento.
void Financiamento::setValorParcela(double v)
Referenced by Financiamento.
void Financiamento::setValorTotalFinanciado(int nVezes, double vParcela)
Referenced by Financiamento.