State
State::State()
virtual void State::constructFromState(QObject *form)=0
Referenced by construct.
virtual void State::getInformationAndSaveState(QObject *form)=0
Referenced by canGoNextState.
virtual bool State::infoIsValid()=0
Referenced by canGoNextState.
virtual void State::displayErroMsg()=0
Referenced by canGoNextState.
virtual void State::saveInContext()
Referenced by canGoNextState.
bool State::canGoNextState(QObject *form)
References getInformationAndSaveState, infoIsValid, displayErroMsg, saveInContext.
void State::construct(QObject *form)
References constructFromState.