InvestmentContext
Investimento* InvestmentContext::investimento
Financiamento* InvestmentContext::financiamento
QString* InvestmentContext::investment
InvestmentContext * InvestmentContext::instance
InvestmentContext::InvestmentContext()
static InvestmentContext* InvestmentContext::getInstance()
Referenced by StateFour::constructFromState, StateOne::saveInContext, StateThree::saveInContext, StateTwo::saveInContext.
Financiamento * InvestmentContext::getFinanciamento() const
void InvestmentContext::setFinanciamento(Financiamento *value)
Referenced by StateOne::saveInContext.
Investimento * InvestmentContext::getInvestimento() const
void InvestmentContext::setInvestimento(Investimento *value)
Referenced by StateThree::saveInContext.
QString * InvestmentContext::getInvestment() const
void InvestmentContext::setInvestment(QString *value)
Referenced by StateTwo::saveInContext.